server:
  port: 8083
spring:
  application:
    name: "Report"
  devtools:
    add-properties: false
  profiles:
    include: null
entrypoint:
  sqs:
    region: "${AWS_REGION}"
    queueName: "${AWS_APPROVED_LOANS_QUEUE_NAME}"
    queueUrl: "${AWS_APPROVED_LOANS_QUEUE_URL}"
    accessKeyId: "${AWS_ACCESS_KEY_ID}"
    secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
